#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

MODEL_PATH=${MODEL_PATH:-Qwen/Qwen2.5-Coder-3B}
EXP_NAME=${EXP_NAME:-selfplay_grpo_test}
N_GPUS_PER_NODE=${N_GPUS_PER_NODE:-2}
TENSOR_MODEL_PARALLEL_SIZE=${TENSOR_MODEL_PARALLEL_SIZE:-2}
ULYSSES_SEQUENCE_PARALLEL_SIZE=${ULYSSES_SEQUENCE_PARALLEL_SIZE:-2}
PPO_MICRO_BATCH_SIZE_PER_GPU=${PPO_MICRO_BATCH_SIZE_PER_GPU:-8}
ROLLOUT_GPU_MEMORY_UTILIZATION=${ROLLOUT_GPU_MEMORY_UTILIZATION:-0.4}
PROPOSER_INTRINSIC_MODE=${PROPOSER_INTRINSIC_MODE:-none}
TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE:-8}
VAL_BATCH_SIZE=${VAL_BATCH_SIZE:-32}
TOTAL_EPOCHS=${TOTAL_EPOCHS:-1}
SAVE_FREQ=${SAVE_FREQ:--1}
TEST_FREQ=${TEST_FREQ:--1}

export MODEL_PATH EXP_NAME N_GPUS_PER_NODE TENSOR_MODEL_PARALLEL_SIZE
export ULYSSES_SEQUENCE_PARALLEL_SIZE PPO_MICRO_BATCH_SIZE_PER_GPU
export ROLLOUT_GPU_MEMORY_UTILIZATION PROPOSER_INTRINSIC_MODE TRAIN_BATCH_SIZE VAL_BATCH_SIZE
export TOTAL_EPOCHS SAVE_FREQ TEST_FREQ

exec "${SCRIPT_DIR}/../run_grpo.sh" "$@"
