#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

MODEL_PATH=${MODEL_PATH:-Qwen/Qwen3-4B-Base}
EXP_NAME=${EXP_NAME:-selfplay_grpo_qwen3_4b_bootstrap}
N_GPUS_PER_NODE=${N_GPUS_PER_NODE:-2}
TENSOR_MODEL_PARALLEL_SIZE=${TENSOR_MODEL_PARALLEL_SIZE:-2}
if [[ -z "${ULYSSES_SEQUENCE_PARALLEL_SIZE+x}" ]]; then
  if [[ "${N_GPUS_PER_NODE}" -ge 8 ]]; then
    ULYSSES_SEQUENCE_PARALLEL_SIZE=4
  else
    ULYSSES_SEQUENCE_PARALLEL_SIZE=2
  fi
fi
TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE:-8}
MAX_PROMPT_LENGTH=${MAX_PROMPT_LENGTH:-3072}
MAX_RESPONSE_LENGTH=${MAX_RESPONSE_LENGTH:-2048}
CONTENT_MAX_LENGTH=${CONTENT_MAX_LENGTH:-2800}
PPO_MICRO_BATCH_SIZE_PER_GPU=${PPO_MICRO_BATCH_SIZE_PER_GPU:-1}
PPO_MAX_TOKEN_LEN_PER_GPU=${PPO_MAX_TOKEN_LEN_PER_GPU:-8192}
LOG_PROB_MICRO_BATCH_SIZE_PER_GPU=${LOG_PROB_MICRO_BATCH_SIZE_PER_GPU:-8}
MAX_NUM_BATCHED_TOKENS=${MAX_NUM_BATCHED_TOKENS:-8192}
ACTOR_USE_DYNAMIC_BSZ=${ACTOR_USE_DYNAMIC_BSZ:-True}
ACTOR_PARAM_OFFLOAD=${ACTOR_PARAM_OFFLOAD:-True}
ACTOR_OPTIMIZER_OFFLOAD=${ACTOR_OPTIMIZER_OFFLOAD:-True}
ROLLOUT_GPU_MEMORY_UTILIZATION=${ROLLOUT_GPU_MEMORY_UTILIZATION:-0.4}
PROPOSER_INTRINSIC_MODE=${PROPOSER_INTRINSIC_MODE:-none}
TASK=${TASK:-pred_code_o}
REWARD_MODE=${REWARD_MODE:-grounded}
TOTAL_EPOCHS=${TOTAL_EPOCHS:-1}
SAVE_FREQ=${SAVE_FREQ:--1}
TEST_FREQ=${TEST_FREQ:--1}

export MODEL_PATH EXP_NAME N_GPUS_PER_NODE TENSOR_MODEL_PARALLEL_SIZE
export ULYSSES_SEQUENCE_PARALLEL_SIZE PPO_MICRO_BATCH_SIZE_PER_GPU
export TRAIN_BATCH_SIZE MAX_PROMPT_LENGTH MAX_RESPONSE_LENGTH CONTENT_MAX_LENGTH
export PPO_MAX_TOKEN_LEN_PER_GPU LOG_PROB_MICRO_BATCH_SIZE_PER_GPU
export MAX_NUM_BATCHED_TOKENS ACTOR_USE_DYNAMIC_BSZ
export ACTOR_PARAM_OFFLOAD ACTOR_OPTIMIZER_OFFLOAD
export ROLLOUT_GPU_MEMORY_UTILIZATION PROPOSER_INTRINSIC_MODE TASK REWARD_MODE
export TOTAL_EPOCHS SAVE_FREQ TEST_FREQ

exec "${SCRIPT_DIR}/../run_grpo.sh" "$@"
